version: "3.9"  # optional since v1.27.0
services:
  main-app-micro1:
    build: ./micro1
    environment:
      PORT: 10000
    networks:
      - bus
      - main-app-micro-network
      - proxy
    depends_on:
      - db-main-app-micro
      - bus
      - cache-main-app-micro
  db-main-app-micro:
    image: postgres:12.6-alpine
#    build: ./db-main-app-micro
    container_name: postgres-12.6-main-app
    restart: unless-stopped
    volumes:
      - ./db-main-app-micro:/docker-entrypoint-initdb.d
#      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '15432:5432'
    networks:
      - main-app-micro-network
  cache-main-app-micro:
    image: redis
    networks:
      - main-app-micro-network

  statistic-app-micro1:
    build: ./micro2
    environment:
      PORT: 11000
    networks:
      - bus
      - statistics-app-micro-network
      - proxy
    depends_on:
      - db-statistics-app-micro
      - bus
      - cache-statistic-app-micro
  db-statistics-app-micro:
    image: postgres:12.6-alpine
    container_name: postgres-12.6-statistics-app
    restart: unless-stopped
    volumes:
      - ./db-statistics-app-micro:/docker-entrypoint-initdb.d
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '15433:5432'
    networks:
      - statistics-app-micro-network
  cache-statistic-app-micro:
    image: redis
    networks:
      - statistics-app-micro-network

  bus:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bus

  nginx:
    image: nginx:latest
    ports:
       - "80:80"
    depends_on:
      - main-app-micro1
      - statistic-app-micro1
    networks:
      - proxy
#    links:
#      - main-app-micro
#      - statistic-app-micro
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
networks:
  proxy:
    driver: bridge
  main-app-micro-network:
    driver: bridge
  statistics-app-micro-network:
    driver: bridge
  bus:
    driver: bridge